# Generated by Django 5.1.7 on 2025-03-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("ticker", models.CharField(max_length=6)),
                ("lower_tunnel", models.FloatField()),
                ("upper_tunnel", models.FloatField()),
                ("check_period", models.FloatField()),
            ],
        ),
    ]
