# Generated by Django 5.1.7 on 2025-03-21 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_assets_last_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="assets",
            name="last_check",
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
