# Generated by Django 5.1.7 on 2025-03-21 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_assets_last_check"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assets",
            name="last_check",
        ),
    ]
