# Generated by Django 5.1.7 on 2025-03-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_assets_last_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="assets",
            name="last_price",
            field=models.FloatField(default=0),
        ),
    ]
